using System;
using System.Runtime.InteropServices;
using Microsoft.CodeAnalysis;
using SourceGenerator.CodeTemplates;

namespace SourceGenerator.Utils;

public static class SourceProductionContextUtil
{
    public static void AddSource<T>(
        this SourceProductionContext context,
        string hintName,
        CodeTemplate<T> codeTemplate,
        T executeSource
    )
    {
        var source =
            $$"""
              //------------------------------------------------------------------------------
              // <auto-generated>
              //     This code was generated by a Haikara.SourceGenerator.
              //     Runtime FrameworkDescription:{{RuntimeInformation.FrameworkDescription}}
              //
              //     Changes to this file may cause incorrect behavior and will be lost if
              //     the code is regenerated.
              // </auto-generated>
              //------------------------------------------------------------------------------
              // Generated: {{DateTime.Now:yyyy-MM-dd hh:mm:ss}}

              {{codeTemplate.BuildCodeString(executeSource)}}

              """;


        context.AddSource(
            hintName: hintName,
            source: source
        );
    }
}