//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceGenerator.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SourceGenerator.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haikara Analyzer.
        /// </summary>
        public static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods with the ClickCommand attribute must have only EventBase as an argument..
        /// </summary>
        public static string ErrorClickCommandHasNoEventBaseArgument {
            get {
                return ResourceManager.GetString("ErrorClickCommandHasNoEventBaseArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one class with the HaikaraUI attribute can be defined in a single file..
        /// </summary>
        public static string ErrorMultipleHaikaraUiAttributeClass {
            get {
                return ResourceManager.GetString("ErrorMultipleHaikaraUiAttributeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesting of classes with the HaikaraUI attribute is prohibited..
        /// </summary>
        public static string ErrorNestedHaikaraUiAttributeClass {
            get {
                return ResourceManager.GetString("ErrorNestedHaikaraUiAttributeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The View class must have the same file name and class name..
        /// </summary>
        public static string ErrorNotMatchedFileNameAndClassName {
            get {
                return ResourceManager.GetString("ErrorNotMatchedFileNameAndClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes with the HaikaraUI attribute must implement IHaikaraView or IHaikaraStyle..
        /// </summary>
        public static string WarningHaikaraUiHasNotImplementedValidInterface {
            get {
                return ResourceManager.GetString("WarningHaikaraUiHasNotImplementedValidInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The associated .uxml file was not found..
        /// </summary>
        public static string WarningMissingRelatedUxmlFile {
            get {
                return ResourceManager.GetString("WarningMissingRelatedUxmlFile", resourceCulture);
            }
        }
    }
}
